### ISSUE TITLE
请问应该要如何使用啊？

### ISSUE THREAD

**Issue by kdqiu** [1ywan/zotero-odh#39]
你好，谢谢开发这个插件，我使用过相对应的浏览器插件，很有用。请问如何使用该插件啊，安装后没有作用。

**Comment by 1ywan** [comment]
hi，感谢尝试，release 的是第一个版本，确实存在一些 bug，和一些操作上的 hacking，并不方便。我会在近期更新一个 release 版本，并附上依赖的安装说明。

**Comment by 1ywan** [comment]
> 你好，谢谢开发这个插件，我使用过相对应的浏览器插件，很有用。请问如何使用该插件啊，安装后没有作用。

可以试试最新发布的这个版本，核心的划词翻译和 anki 的功能应该是好的了，这个单我就关闭了
